# 13. 예외처리

### 1. 예외처리

오류 발생하면 프로그램은 에러 출력하며 강제 종료되거나 이상한 동작을 함

이러한 오류를 안전하게 처리하고 바로 강제종료 되지 않고 오류 발생 후 처리할 루틴을 실행하고자

할때 예외처리를 사용함



1. 예외처리의 가장 기본적인 형태 : 

   ```python
   try : 
   	시도할 코드
   except:
   	에러가 발생했을 경우 실행할 코드
   ```

   리스트의 범위를 넘어간 에러를 테스트해본다.

   

2. 여러가지 예외를 구분할 경우의 형태

   ```python
   try : 
   	시도할 코드
   except <예외 클래스1> :
       에러클래스 1에 해당할 때 실행할 코드
   except <예외 클래스2> :
       에러클래스 2에 해당할 때 실행할 코드
   except <예외 클래스3> :
       에러클래스 3에 해당할 때 실행할 코드
   ... 
   ```

   

3. 예외사항을 변수로 사용할 경우의 형태

   ```python
   try : 
   	시도할 코드
   except <예외클래스> as <변수명>:
   		<변수명>을 사용한 코드
   ```



### 2. try ~ else

`else`문은 `try`이후 예외가 발생하지 않을 경우 실행된다.

```python
try:
	시도할 코드
except:
	예외 발생시 실행 코드
else:
	예외가 발생하지 않았을 시 실행할 코드
```



### 3. try ~ finally

`finally `문은  try 이후 예외가 발생하건, 하지 않건 무조건 마지막에 실행된다.



### 4. 예외 발생시키는 방법

`raise`구문을 사용한다.



### 5. 예외 만들기

내장 클래스 `Exception`을 상속받아 커스텀 예외를 만들 수 있다. 초기화 메서드에서 예외에서 처리할 데이터를 받고, print 문으로 사용되고 싶다면 `__str__` 메서드를 오버라이드 해준다.